### ISSUE TITLE
Make GitHubChecksContext public outside of package

### ISSUE THREAD

**Issue by agaudreault-jive** [jenkinsci/github-checks-plugin#104]
We want to start using this plugin to send GitHub status check, but our pipelines do not always use GIT or GitHub SCM. For instance, in some cases we use a generic pipeline and use environment variables/parameters to checkout the correct sources. By default, the GitSCM will not be configured to the repository we want to send checks to.

Would it make sense to have `GitHubChecksContext` public, so we can create a new context and a new `ChecksPublisherFactory` ?

**Comment by XiongKezhi** [comment]
of course, that makes sense
