### ISSUE TITLE
How to use this with private repos?

### ISSUE THREAD

**Issue by cnelson** [jenkinsci/github-checks-plugin#113]
When attempting to follow the documentation to setup the github branch source plugin to use app credentials instead of username/password (or token), private repos are not discovered so an app credential cannot be used.

There doesn't seem to be a way to manually specify the credential to use, if the discovered one is not an app credential

What am I missing here?

**Comment by XiongKezhi** [comment]
have you installed that app on your repository? https://docs.github.com/en/developers/apps/installing-github-apps#installing-your-private-github-app-on-your-repository
