### ISSUE TITLE
Install an app???

### ISSUE THREAD

**Issue by okainov** [jenkinsci/github-checks-plugin#128]
>Prerequsite: only GitHub App with proper permissions can publish checks, this guide helps you authenticate your Jenkins as a GitHub App.

Is it really required? We currently use just normal Github API for this (https://docs.github.com/en/rest/reference/repos#create-a-commit-status), why is it required here to use an app??

**Comment by timja** [comment]
The checks API requires a GitHub app

https://docs.github.com/en/rest/reference/checks
