### ISSUE TITLE
Allow Reducing the Verbosity of the Logging

### ISSUE THREAD

**Issue by jamandbees** [jenkinsci/github-checks-plugin#155]
### Feature Request

Since installing the Github Checks plugin, we are seeing log entries on every build from the plugin. These have caused some confusion for the users of our build system. They look like the following:

> 08:57:03  [GitHub Checks] Causes for no suitable publisher found: 
> 08:57:03  [GitHub Checks] Trying to resolve checks parameters from GitHub SCM...
> 08:57:03  [GitHub Checks] Job does not use GitHub SCM
> 08:57:03  [GitHub Checks] Trying to resolve checks parameters from Git SCM...
> 08:57:03  [GitHub Checks] No GitHub app credentials found: '<redacted creds ID>'
> 08:57:03  [GitHub Checks] See: https://github.com/jenkinsci/github-branch-source-plugin/blob/master/docs/github-app.adoc
> 08:57:03  [GitHub Checks] Job does not have valid credentials
> 08:57:03  [Checks API] No suitable checks publisher found.

It would be a nice feature to be able to turn these log entries off, as the use-case in our build system does not need this information.

**Comment by XiongKezhi** [comment]
I think this could be added here (not in the API) as a project-level configuration @timja
