### ISSUE TITLE
`java.util.UnknownFormatConversionException: Conversion = ';'` from GitHubChecksPublisher.publish

### ISSUE THREAD

**Issue by jglick** [jenkinsci/github-checks-plugin#161]
Seen in https://ci.jenkins.io/job/Plugins/job/jjwt-api-plugin/job/PR-21/1/console building https://github.com/jenkinsci/jjwt-api-plugin/pull/21:

```
 ​[GitHub Checks] GitHub check (name: Jenkins, status: COMPLETED) has been published
 ​java.util.UnknownFormatConversionException: Conversion = ';
 ​	at java.base/java.util.Formatter.checkText(Formatter.java:2732
 ​	at java.base/java.util.Formatter.parse(Formatter.java:2718
 ​	at java.base/java.util.Formatter.format(Formatter.java:2655
 ​	at java.base/java.util.Formatter.format(Formatter.java:2609
 ​	at java.base/java.lang.String.format(String.java:2897
 ​	at io.jenkins.plugins.util.PluginLogger.log(PluginLogger.java:47
 ​	at io.jenkins.plugins.checks.github.GitHubChecksPublisher.publish(GitHubChecksPublisher.java:92
 ​	at io.jenkins.plugins.checks.status.BuildStatusChecksPublisher.publish(BuildStatusChecksPublisher.java:63
 ​	at io.jenkins.plugins.checks.status.BuildStatusChecksPublisher.access$000(BuildStatusChecksPublisher.java:42
 ​	at io.jenkins.plugins.checks.status.BuildStatusChecksPublisher$JobCheckoutListener.lambda$onCheckout$0(BuildStatusChecksPublisher.java:174
 ​	at java.base/java.util.Optional.ifPresent(Optional.java:183
 ​	at io.jenkins.plugins.checks.status.BuildStatusChecksPublisher$JobCheckoutListener.onCheckout(BuildStatusChecksPublisher.java:174
 ​	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:150
 ​	at …
```

**Comment by KalleOlaviNiemitalo** [comment]
I see, java.util.logging.Logger has a [log(Level level, String msg, Throwable thrown)](https://docs.oracle.com/javase/8/docs/api/java/util/logging/Logger.html#log-java.util.logging.Level-java.lang.String-java.lang.Throwable-) method that takes a literal string, but PluginLogger has only [log(String format, Object... args)](https://github.com/jenkinsci/plugin-util-api-plugin/blob/7d3ca35b4df5ef7ead71a151d9747ce0d231a80b/src/main/java/io/jenkins/plugins/util/PluginLogger.java#L45-L48).  BuildStatusChecksPublisher then calls both with the same string.

<https://github.com/jenkinsci/github-checks-plugin/blob/1c4caf9289437bfe54dc304e50d485d24c56e6d3/src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisher.java#L89-L93>

PluginLogger.log has a `@FormatMethod` annotation, though. Would that allow the bug to be detected in static analysis?

**Comment by jglick** [comment]
Why not just bypass `PluginLogger` in this case and print directly to the build log however you prefer?

**Comment by jglick** [comment]
Which is preferable anyway in the case of an unexpected exception. Typically via https://javadoc.jenkins.io/hudson/model/TaskListener.html#error-java.lang.String- + https://javadoc.jenkins.io/hudson/Functions.html#printStackTrace-java.lang.Throwable-java.io.PrintWriter-

**Comment by KalleOlaviNiemitalo** [comment]
AFAIK, this can be called from [BuildStatusChecksPublisher.JobScheduledListener.onEnterWaiting](https://github.com/jenkinsci/checks-api-plugin/blob/9bbf5bc1d34781cb0cba69eefe7a30fbd5f21f15/src/main/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisher.java#L144-L145) before there is a Run and a build log.

**Comment by timja** [comment]
We don't have direct access to the task listener here -.-

Looks like more a bug with plugin-util-api-plugin @uhafner.

If there's no args being passed we shouldn't try and format it?

It's a shame we don't have the actual io exception either, i guess it's in the system log if anyone wants to dig it out

**Comment by KalleOlaviNiemitalo** [comment]
I expect `buildLogger.log("%s", message + e)` would suffice here.

**Comment by jglick** [comment]
> it's in the system log if anyone wants to dig it out

No idea. I do not have access. Whatever the original error was, it seems to have been transient, as a simple rebuild worked.

**Comment by timja** [comment]
> I expect `buildLogger.log("%s", message + e)` would suffice here.

yes probably
