### ISSUE TITLE
Truncate text and summary for check reporting to 65535 characters

### ISSUE THREAD

**Issue by patrickhuy** [jenkinsci/github-checks-plugin#194]
### Feature Request

The current maximum size for the fields text and summary supported by GitHub is 65535, it would be good if the plugin could truncate the text if it exceeds this length.

See https://github.community/t/undocumented-65535-character-limit-on-requests/117564/3

**Comment by KalleOlaviNiemitalo** [comment]
This was already implemented, see here: <https://github.com/jenkinsci/github-checks-plugin/blob/9e2588962c360a17ba4372d8fa541b604843ff5a/src/main/java/io/jenkins/plugins/checks/github/GitHubChecksDetails.java#L173-L178>

If that isn't working, then which versions of checks-api-plugin and github-checks-plugin are you using?

**Comment by timja** [comment]
and how are you using the checks API? As I think consumers need to use the special API as well (junit was updated for it).

**Comment by patrickhuy** [comment]
You are of course right, I'm sorry! I was apparently running an old version of the plugin.
