### ISSUE TITLE
GitHub Check does not get updated/dismissed after rebuild

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/github-checks-plugin#21]
Reporting on behalf of @jglick , the issue appears on ci.jenkins.io after deploying the plugin. Reporting to this plugin, because "dismiss" functionality is unlikely common. Feel free to move to checks API>

https://github.com/jenkinsci/suppress-stack-trace-plugin/pull/5/checks?check_run_id=950988935 was reported for https://ci.jenkins.io/job/Plugins/job/suppress-stack-trace-plugin/job/PR-5/1/ which is indeed failed. After that, https://ci.jenkins.io/job/Plugins/job/suppress-stack-trace-plugin/job/PR-5/2/ succeeded, yet the check status was not updated.

![image](https://user-images.githubusercontent.com/3000480/89529241-aba21000-d7ec-11ea-902b-94dae4f8605c.png)

**Comment by XiongKezhi** [comment]
Seems like a problem in the run listener, I'll dig into it and likely to transfer this issue to checks API.

**Comment by XiongKezhi** [comment]
I can't reproduce this issue now, I introduced a bug and open a PR: https://github.com/XiongKezhi/codingstyle/pull/6/commits, then fixed the bug, however, both checks are published correctly.

Also, according to the console of your PR: https://ci.jenkins.io/job/Plugins/job/suppress-stack-trace-plugin/job/PR-5/2/console, the check has been published successfully: 
![截屏2020-08-12 下午2 47 47](https://user-images.githubusercontent.com/30348893/89986883-c0c8e400-dcaf-11ea-8036-c5b3ef2797a5.png)

**Comment by XiongKezhi** [comment]
We found the problem, it's because we are always publishing checks for the head commit, so if the first build finishes later than the second build, the check for the first build will be published to the second build (head commit).  Thanks for your report, I'll solve this problem in the next release.

**Comment by XiongKezhi** [comment]
Fixed by resolving the commit SHA from the build after checking out instead of always fetching head commit from GitHub.
