### ISSUE TITLE
Having trouble customizing GitHub Checks page view

### ISSUE THREAD

**Issue by grvvy** [jenkinsci/github-checks-plugin#215]
## Summary

I'm new to Jenkins/CI and web/REST development in general, but I set up a multibranch pipeline project and a basic GH app connected to cmee to handle my webhooks.

I then installed the Checks API plugin along with the GitHub Checks plugin and I'm successfully seeing some output in my Checks view on GitHub:

![Screenshot from 2021-10-26 16-38-29](https://user-images.githubusercontent.com/13262366/138983505-5e0fb70a-5f3a-4f7d-a0fd-3d1b09f69527.jpg)

Since then I've skimmed some GH App documentation and watched the final demo video but I'm having trouble figuring out how to customize this view. I see the "Consume API - Create Checks" section but I'm not sure where that code implementation would even go. 

Is there a way to view the code that is being run in the background that's giving me this default view after installing the app?. 

I'm also not sure if that's totally necessary or if I'm missing something simple to achieve a nicer looking checks page like this one:

![Screenshot from 2021-10-26 16-59-16](https://user-images.githubusercontent.com/13262366/138983471-317982fe-aed7-4ae0-af51-e3baf6a53cfc.png)

Some specific examples of the improvements I'd like to have from the second screenshot are: clickable build steps that display some build log info instead of plain bullet points outlining my pipeline stages.

[Pipeline defined here](https://github.com/grvvy/greatfet/blob/master/Jenkinsfile)

My only theory is that maybe it doesn't handle the fact that each stage simply runs a shell script and so the nice features of the second screenshot aren't working; but I'm also unsure if those are supposed to work by default right after installing the plugin.

Cheers!

**Comment by SaranshIam** [comment]
Hi @KalleOlaviNiemitalo 


> The Markdown text for the checks report is generated by [FlowExecutionAnalyzer in checks-api-plugin](https://github.com/jenkinsci/checks-api-plugin/blob/v1.7.2/src/main/java/io/jenkins/plugins/checks/status/FlowExecutionAnalyzer.java). If you want a different format, then it could be implemented in a few ways:
> 
> * Edit checks-api-plugin so that FlowExecutionAnalyzer formats the Markdown differently. I have a stalled PR [Simplify status checks output for "error" and "unstable" steps checks-api-plugin#125](https://github.com/jenkinsci/checks-api-plugin/pull/125) that changes it somewhat but doesn't add bullet points.
> * Edit checks-api-plugin to make the Markdown formatting an extension point, and publish another plugin that formats it differently.
> * Disable "status checks" in the project in Jenkins, and instead write a pipeline library to format the Markdown and use the `publishChecks` step to publish it to GitHub. This would be difficult to implement.
> 
> I'm not sure it would be possible for FlowExecutionAnalyzer to generate bullet points for pipeline stages or steps that haven't even started yet.

Can you guide me on how should I display a table on the github checks page.
I can create a markdown shared lib. in my pipeline , but I am not sure how to display it on github checks page.

**Comment by KalleOlaviNiemitalo** [comment]
@SaranshIam, if you want to add a table to a check that Jenkins already publishes to GitHub, I think you need to edit the Java code in some plugin: github-checks, checks-api, or whatever plugin publishes the check to checks-api.

If you instead want to publish an entirely new check that includes a table, the [`publishChecks` step](https://www.jenkins.io/doc/pipeline/steps/checks-api/#publishchecks-publish-customized-checks-to-scm-platforms) will be the easiest way to do that from a pipeline.

**Comment by SaranshIam** [comment]
@KalleOlaviNiemitalo Thank You!
I am publishing entirely new checks , but I still do not understand how publishChecks will help me output it in a table format? 
I mean which of the parameters that the plugin takes would help me to format output as a table?

**Comment by KalleOlaviNiemitalo** [comment]
The `summary` and `text` parameters of the `publishChecks` step support Markdown. I think you could input your table via one of those.

**Comment by SaranshIam** [comment]
Ok I will try this. Thanks a lot for all the help @KalleOlaviNiemitalo !!
