### ISSUE TITLE
Manual builds throw an exception when they run

### ISSUE THREAD

**Issue by LevitatingKraken** [jenkinsci/github-checks-plugin#370]
### Jenkins and plugins versions report

github-checks:545.v79a_a_68b_ca_682

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller

### Reproduction steps

Create a build that is triggered manually

### Expected Results

Don't try to publish github results or make "Status Checks Properties -> Skip publishing status checks" work

### Actual Results

Log of the Jenkins job gets this:
`[GitHub Checks] Failed Publishing GitHub checks: org.kohsuke.github.HttpException: {"message":"You must authenticate via a GitHub `

Inside Jenkins we see this exception:
`org.kohsuke.github.HttpException: {"message":"You must authenticate via a GitHub App.","documentation_url":"https://docs.github.com/rest/checks/runs#create-a-check-run"}
	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:62)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:473)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:435)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:403)`

### Anything else?

Make an option to update Github only if it's a PR/Branch

**Comment by timja** [comment]
You’ll need to explain more how your job is setup. This should publish just fine on builds that are triggered manually

**Comment by LevitatingKraken** [comment]
@timja This is a groovy job taken from SCM (Github).
Every build we get these exceptions shown above.
Trying to set "Skip" or "suppress" didn't help

**Comment by LevitatingKraken** [comment]
Adding more information.
1 manual build manages to update the check
If I copy that build to another build it fails updating the check.
I thought it might be because all the checks have the same name? (all go to the same repo)
But renaming the check didn't really do anything and the check is still called "Jenkins"
![image](https://github.com/jenkinsci/github-checks-plugin/assets/88397999/b7203010-ac9b-43ef-8bf4-156fd6dc03ea)
