### ISSUE TITLE
"github checks plugin" does not work in jenkins  2.426.3-lts

### ISSUE THREAD

**Issue by raajaaDheeRaajaa** [jenkinsci/github-checks-plugin#381]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

jenkins  2.426.3-lts

### Reproduction steps

"github checks plugin" does not work in jenkins  2.426.3-lts

### Expected Results

"github checks plugin" does not work in jenkins  2.426.3-lts

### Actual Results

"github checks plugin" does not work in jenkins  2.426.3-lts

**Comment by timja** [comment]
there is no actionable information here, doesn't work is not enough of a bug report
