### ISSUE TITLE
Re-enable skipped conclusion

### ISSUE THREAD

**Issue by beikov** [jenkinsci/github-checks-plugin#393]
### What feature do you want to see added?

The skipped conclusion was at some point changed to be represented as failed in GitHub as can be seen here:
* https://github.com/jenkinsci/github-checks-plugin/issues/63
* https://github.com/jenkinsci/github-checks-plugin/pull/64

The [GitHub API documentation](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run--parameters) clearly states that skipped is valid and I even tested this myself as can be seen here: https://github.com/beikov/hibernate-github-bot-test/runs/27508834193

I propose to properly model the skipped conclusion again.

**Comment by beikov** [comment]
Thanks for the quick merge @timja
When can I expect a release with that fix? :)

**Comment by timja** [comment]
https://github.com/jenkinsci/github-checks-plugin/releases/tag/581.va_9669c91d6cb_

**Comment by beikov** [comment]
Is it possible that the publishing of the release failed? I don't see it yet on https://plugins.jenkins.io/github-checks/

**Comment by timja** [comment]
I do:
![image](https://github.com/user-attachments/assets/be78f5ba-9840-49b4-b6a1-fbc6809b28b5)

**Comment by beikov** [comment]
Oh wow, that page seems to have very aggressive caching. After clearing caches it shows up. Sorry for the noise.

**Comment by timja** [comment]
I believe its behind fastly and different locations may have different caches yes.
