### ISSUE TITLE
The Jenkins plugin is not compatible with GitHub Enterprise servers as it attempts to contact github.com

### ISSUE THREAD

**Issue by krishgcek** [jenkinsci/github-checks-plugin#411]
### Issue with Jenkins Plugin for GitHub Enterprise Servers

We have encountered an issue with the Jenkins plugin when used with GitHub Enterprise servers. The plugin currently tries to connect to `github.com`, which is problematic for our environment that utilizes a self-hosted GitHub Enterprise instance.

#### Issue Details:
- The plugin fails to utilize the GitHub URL configured in the Jenkins multibranch project settings.
- This results in incorrect behavior and failures when attempting to publish checks or interact with the repository.

#### Feature Request:
We would like to request an enhancement to the plugin that would allow users to specify the following:

1. **GitHub URL and Repository**:
   - A feature to provide a custom GitHub URL and repository when invoking the `publishChecks` step. This would allow the plugin to correctly target the GitHub Enterprise instance.
   - Additionally, the plugin should be able to retrieve the GitHub URL directly from the branch source plugin configuration, ensuring it always uses the correct endpoint based on the project settings.

2. **Credentials Handling**:
   - The ability to specify credentials directly in the `publishChecks` step.
   - Alternatively, allow for the retrieval of credentials via the `withCredentials` step in Jenkins, ensuring that credentials management is streamlined and secure.

3. **Environment Variable Support**:
   - Support for environment variables to specify the GitHub URL and credentials. This would enable more flexible configuration options, especially in pipeline scripts where dynamic values may be required.

### What Operating System are you using (both controller, and any agents involved in the problem)?

we are using link for both jenkins server and node

### Reproduction steps

- create a multibranch project and specify git enterprise repo url and github app credentials. 
- use a token based credentials during checkout
- call publishCheck step

### Expected Results

checks are published in git enterprise 

### Actual Results

the plugin contacts github.com.
 hudson.remoting.ProxyException: org.kohsuke.github.HttpException: {"message":"A JSON web token could not be decoded","documentation_url":"https://docs.github.com/rest","status":"401"}
11:37:29  	at PluginClassLoader for github-api//org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:72)
11:37:29  	at PluginClassLoader for github-api//org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:504)
11:37:29  	at PluginClassLoader for github-api//org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:464)
11:37:29  	at PluginClassLoader for github-api//org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:427)
11:37:29  	at PluginClassLoader for github-api//org.kohsuke.github.Requester.fetch(Requester.java:85)
11:37:29  	at PluginClassLoader for github-api//org.kohsuke.github.GitHub.getApp(GitHub.java:1189)
11:37:29  	at PluginClassLoader for github-branch-source//org.jenkinsci.plugins.github_branch_source.GitHubAppCredentials.generateAppInstallationToken(GitHubAppCredentials.java:218)
11:37:29  Also:   hudson.remoting.ProxyException: org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 9936870d-2cf4-4699-824d-34d49a02c0dc
11:37:29  Caused: hudson.remoting.ProxyException: java.lang.IllegalArgumentException: Couldn't authenticate with GitHub app ID...

### Anything else?

normal git status notification is working.
GitHub has been notified of this commit’s build result

**Comment by timja** [comment]
It gets the API url off the GitHub apps credential:
https://github.com/jenkinsci/github-checks-plugin/blob/a8f21936d0e969933805f7272223a28e1a29ca40/src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisher.java#L78C63-L78C72

The API url is visible if you've configured another GitHub server in the system global configuration:
https://github.com/jenkinsci/github-branch-source-plugin/blob/50351eb7dd13333d4a9661cc055314015d697314/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java#L668

API url will be below app id from above private key:
https://github.com/jenkinsci/github-branch-source-plugin/blob/50351eb7dd13333d4a9661cc055314015d697314/src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials/config.jelly#L9

**Comment by krishgcek** [comment]
I was able to configure the apiurl using groovy directly.
