### ISSUE TITLE
The plugin is not usable with GitHub Enterprise

### ISSUE THREAD

**Issue by UncleIS** [jenkinsci/github-checks-plugin#49]
Hello, everyone!

Thanks for the work that you are doing on the plugin! We are using Jenkins in an enterprise environment, where there is a Enterprise GitHub installation running. 

It would be very nice to use this plugin with the installation that we have, but, as of now, that doesn't work, unfortunately.

With the current implementation, the plugin checks for the validity of the GH URL, validating the submitted string as follows:

https://github.com/jenkinsci/github-checks-plugin/blob/a0c5db0f6fd1bf883943c1d796948d033a539564/src/main/java/io/jenkins/plugins/checks/github/GitSCMChecksContext.java#L138-L140

The values of the GIT_PROTOCOL and HTTPS_PROTOCOL constants are as follows:
https://github.com/jenkinsci/github-checks-plugin/blob/a0c5db0f6fd1bf883943c1d796948d033a539564/src/main/java/io/jenkins/plugins/checks/github/GitSCMChecksContext.java#L20-L21

This means that anything having its hostname different from `github.com` would not pass this check, and thus the results will not be published, which is what we see:
```
[GitHub Checks] Causes for no suitable publisher found: 
[GitHub Checks] Trying to resolve checks parameters from Git SCM...
[GitHub Checks] No supported GitSCM repository URL: https://github.<some>.<custom>.<domain>/<org>/<repo>
```

At the same time, the multibranch pipelines are able to push GH statuses back to our installation.

Could you have a look at this, please, and let me know if any additional information is needed? 

Thanks!

**Comment by timja** [comment]
@UncleIS are you using 'Git' or 'GitHub' for authentication?

'GitHub' should work, 'Git' is a bit more difficult as we don't know it's GitHub.

**Comment by XiongKezhi** [comment]
> At the same time, the multibranch pipelines are able to push GH statuses back to our installation.

Does this mean you are using the multibranch project for your repository? If so, there may be some configurations are not right, thus it will try to use Git SCM instead of [GitHub SCM Source](https://github.com/jenkinsci/github-checks-plugin/blob/a0c5db0f6fd1bf883943c1d796948d033a539564/src/main/java/io/jenkins/plugins/checks/github/GitHubSCMSourceChecksContext.java).

![image](https://user-images.githubusercontent.com/30348893/92458914-99a2fb00-f1f8-11ea-8a5b-a54bdfec2d11.png)

**Comment by UncleIS** [comment]
Hi!

Thanks for looking into the issue!

We are using a multibranch project indeed with GitHub authentication:

<img width="912" alt="Screen Shot 2020-09-08 at 15 07 44" src="https://user-images.githubusercontent.com/3222295/92475407-052f9d00-f1e6-11ea-95ab-93f2e3c9da09.png">

Here, in the repository HTTPS URL , we have `https://github.<some>.<custom>.<domain>/<org>/<repo>`

**Comment by timja** [comment]
are you using a github app for authentication?

**Comment by XiongKezhi** [comment]
Seems it's a user credential instead of the app credential?

**Comment by UncleIS** [comment]
Yes, these are user credentials.

**Comment by XiongKezhi** [comment]
You need to use GitHub APP credentials and set right permissions for checks: https://github.com/jenkinsci/github-branch-source-plugin/blob/master/docs/github-app.adoc#creating-the-github-app

**Comment by UncleIS** [comment]
Thanks for the hint! I will try that and will get back to you with the result.

**Comment by UncleIS** [comment]
The hint from @XiongKezhi definitely pushed me a bit further: there are no more complaints of the URL, but here is what I'm getting now: 

```
[GitHub Checks] Failed Publishing GitHub checks: org.kohsuke.github.GHFileNotFoundException: https://github.<some>.<custom>.<domain>/api/v3/repos/<org>/<repo>/check-runs {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/enterprise/2.21/v3/checks/runs/#create-a-check-run"}
```

Does that mean that check API is disabled? 

Thanks!

**Comment by XiongKezhi** [comment]
That's caused by your app's permission to write checks. Do you set the write permissions for checks on your APP configurations on GitHub and installed your app to the repository correctly?

**Comment by timja** [comment]
If you click 'Test credentials' I think or 'Validate' from the credential it should give you better error messages

**Comment by UncleIS** [comment]
Hi!

Thanks for the hints and sorry for the delay. It worked indeed after I enabled  the webhook in the application configuration, which I missed during the initial setup. 

Now it is working like a charm. Thanks for your help and sorry for the false alarm!

Best regards.

**Comment by chri7325** [comment]
Hello, I'm also facing the same issue but with a slightly different setup. I'm using the older GitHub pull request builder approach as we're not setup to use Jenkinsfiles but instead use scripts as of now to perform our checks. We also have a single job that handles all of our incoming PRs. Thus, we use a freestyle job using git to clone source. I use a GitHub enterprise app for authentication and when I try to use the git status checks, I get the following

```
[GitHub Checks] Causes for no suitable publisher found: 
[GitHub Checks] Trying to resolve checks parameters from GitHub SCM...
[GitHub Checks] Job does not use GitHub SCM
[GitHub Checks] Trying to resolve checks parameters from Git SCM...
[GitHub Checks] No supported GitSCM repository URL: git@enterprise_server:organization/project.git
[Checks API] No suitable checks publisher found.
```

Is there any way to use this awesome functionality with the older method for handling pull requests?

**Comment by XiongKezhi** [comment]
Is it possible that your URL of enterprise GitHub can start with `git@github.com:`?

https://github.com/jenkinsci/github-checks-plugin/blob/ee265722f878a2aea49cdb6bdf8f3ebd4b7052ff/src/main/java/io/jenkins/plugins/checks/github/GitSCMChecksContext.java#L20

If not, can you provide some valid schemes of the enterprise url so that I can add it.

**Comment by timja** [comment]
@XiongKezhi the domain can be anything but if you look at the system configuration page you’ll see a GitHub enterprise server configuration, you can look those up and see if the domain matches

**Comment by chri7325** [comment]
@XiongKezhi Unfortunately I have no control over what our enterprise server name is but as @timja mentioned as well, I think it would be more robust to not have this restriction as enterprise servers will most likely all follow whatever fits the needs of their company.

**Comment by almostjulian** [comment]
@XiongKezhi  I'm in a similar position, I'm using Github Enterprise as well... I started with a Pipeline project in Jenkins, and I'm just my app credentials to load the Jenkinsfile (my pipeline just has a vanilla `scm checkout` step in terms of connecting to Github Enterprise).   I also get the "Job does not use GitHub SCM/No supported GitSCM repository".  Any advice?

**Comment by XiongKezhi** [comment]
Almost forget about it, sorry... @almostjulian what's your GitHub enterprise URL?

I'll have a try to resolve the API endpoint from the credentials instead of user configuration.

**Comment by timja** [comment]
@XiongKezhi the github enterprise url can be anything, it doesn't matter

> I'll have a try to resolve the API endpoint from the credentials instead of user configuration.

yes, it's available on the credential:
https://github.com/jenkinsci/github-branch-source-plugin/blob/master/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java#L88

**Comment by almostjulian** [comment]
Notice a fix for this was merged, any ETA on a release?

**Comment by XiongKezhi** [comment]
@almostjulian @chri7325 I have released the version with arbitrary enterprise URL support (see https://github.com/jenkinsci/github-checks-plugin/releases/tag/v1.0.9), let us know if there are further questions.

**Comment by chri7325** [comment]
@XiongKezhi I updated the plugin and am now getting this error message

```
[GitHub Checks] Failed Publishing GitHub checks: org.kohsuke.github.GHFileNotFoundException: https://devtopia.esri.com/api/v3/repos/git@devtopia.esri.com:runtime/runtimecore {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.21/v3/repos/#get"}
```

**Comment by timja** [comment]
ha, we're currently parsing the repo out by taking out github.com, the code needs to be smarter, there's probably an API to extract it

**Comment by almostjulian** [comment]
Same issue as @chri7325, the plugin isn't parsing the api url properly.
