### ISSUE TITLE
Rerun build from checks sometimes triggers master branch instead of PR

### ISSUE THREAD

**Issue by timja** [jenkinsci/github-checks-plugin#56]
https://groups.google.com/g/jenkins-infra/c/KkysaBSLs3A

**Comment by XiongKezhi** [comment]
Seems the problem rises from origin PR vs fork PR: https://github.community/t/docs-about-rerequest-check-run/131345 and https://github.community/t/pull-requests-when-rerequest-check-run/131365/2. 

Only the origin PR contains "pull_requests" in the payload, so IMO, we cannot rely on this part to resolve which PR's rerun is triggered.

Maybe we can make use of the `external_id` field? Assign it with the repo-name and branch name like: "jenkinsci/github-checks-plugin/PR-1"
