### ISSUE TITLE
Can't disable/rename check with GitHub Branch Source Plugin

### ISSUE THREAD

**Issue by mew1033** [jenkinsci/github-checks-plugin#72]
I'm using the warnings-ng plugin to publish checks to my GitHub Enterprise server for each code check tool I'm using. However, this plugin is also publishing another check for the entire build itself. Looks like this:
![image](https://user-images.githubusercontent.com/4435733/97365132-cc698700-186a-11eb-8afb-046bff48b682.png)
Is there any way to disable the "Jenkins" check there? For some jobs, I'll want it, but for others that only need a yamllint or something, I only want the warnings-ng check listed.
Based on this line in the readme, I assume it should be possible, but I can't find the setting to make the change.
![image](https://user-images.githubusercontent.com/4435733/97365276-0aff4180-186b-11eb-9d18-11489b9b21d7.png)

**Comment by timja** [comment]
it's a trait / behaviour, I don't think you can disable it without also disabling all other checks.
But you can rename it

**Comment by XiongKezhi** [comment]
The behavior is for the project, so you can only have one configuration for all jobs inside a project.

**Comment by mew1033** [comment]
So does that mean it doesn't work with multi branch pipeline jobs? I tried configuring it in the main project config (not an individual branch/PR) and I still don't see it.

**Comment by XiongKezhi** [comment]
Sorry, we have not released it yet (I should mention it in the README), I thought you were saying the setting for configuring different jobs...😅

One PR left, should be done this week.

**Comment by XiongKezhi** [comment]
hey @mew1033, I just release it (https://github.com/jenkinsci/github-checks-plugin/releases/tag/v1.0.5), please update and try it again.

**Comment by mew1033** [comment]
Fixed it. Thanks!
