### ISSUE TITLE
"Status Checks Properties" becomes necessary in 1.0.6

### ISSUE THREAD

**Issue by medianick** [jenkinsci/github-checks-plugin#79]
Previously, our multibranch pipeline jobs automatically reported the "Jenkins" status check for any jobs using the GitHub App authentication. Starting from 1.0.6 (which we installed on Monday), this behavior stopped, and the workaround is to explicitly add the "Status Checks Properties" section to the multibranch pipeline job configuration.

I would not expect this to be necessary given that it uses the default values (with "Skip publishing status checks" unchecked and the status checks name of "Jenkins").

**Comment by XiongKezhi** [comment]
Thanks, it's my carelessness. I paid attention to the default value after adding the properties behavior but forget to set the default value without the behavior.

**Comment by XiongKezhi** [comment]
Released in v1.0.7.
