### ISSUE TITLE
It would be nice to show each Stage and Step in the check summary

### ISSUE THREAD

**Issue by justinmchase** [jenkinsci/github-checks-plugin#89]
![image](https://user-images.githubusercontent.com/10974/101087115-68c42f00-3577-11eb-8288-c82513e72ef7.png)

Right now the summary just states the conclusion but doesn't show any information about error details or the statuses of individual Stages or Steps.

What would be involved in getting that information into the check status report in github?

**Comment by timja** [comment]
Adding a graph listener https://javadoc.jenkins.io/plugin/workflow-api/org/jenkinsci/plugins/workflow/flow/GraphListener.html

Would allow getting that information into there

cc @jglick who knows that area the best if you want to provide any more info

**Comment by jglick** [comment]
The proprietary equivalent https://docs.cloudbees.com/docs/cloudbees-ci/latest/scm-integration/enabling-scm-reporting#_cloudbees_ci_scm_reporting_feature_benefits indeed uses that interface as a starting point. There are quite a few subtleties there.

**Comment by dgokcin** [comment]
I totally agree. I started using the plugin today and I think it would be great to tell which stage has failed/passed just by looking at the check.

**Comment by timja** [comment]
Would be also nice to know what failed in the GitHub ui without having to go to Jenkins

**Comment by dgokcin** [comment]
@timja Exactly. If there are parallel steps in the build, it gets really hard to figure out what is wrong by looking at the  logs. It would be great  to see everything on a  pull request.

**Comment by justinmchase** [comment]
> Adding a graph listener

@timja Are you saying that, in this plugin it could have a `GraphListener` which listens to events happening about Stages and Steps and then it would call the Github Checks api to send information based on these events?

**Comment by timja** [comment]
> > Adding a graph listener
> 
> @timja Are you saying that, in this plugin it could have a `GraphListener` which listens to events happening about Stages and Steps and then it would call the Github Checks api to send information based on these events?

yes, an example would be stage results and being able to include which step(s) failed.

**Comment by dgokcin** [comment]
@timja @justinmchase I think somehow displaying a custom message instead of "This check concluded as failure." would also be really useful.

**Comment by timja** [comment]
Yes step name that failed could be good

**Comment by justinmchase** [comment]
I believe we first have to modify the https://github.com/jenkinsci/checks-api-plugin to expose these events through the checks api abstraction then we can implement it here.

Talks in progress on that api, sounds like they're going to do some refactoring to support feature additions and we'll look at it after that.

**Comment by timja** [comment]
I expect adding a graph listener would change the design a bit anyway, possibly we’ll end up removing the existing listeners

**Comment by XiongKezhi** [comment]
I haven't explore the graph listener, but if we want to report for each event notified, for now, I can see two ways to add the graph listener:

1. if adding the graph listener would eventually bring incredible changes to the design of the API, then it would make sense to remove the existing listener or move it here in this implementation;

2. if we can finally support updating the checks, then it doesn't matter where we put the graph listener, we can update the status checks to include anything we want.

**Comment by mrginglymus** [comment]
Now that `2.` is possible, I've a rough sketch of something that might work in https://github.com/jenkinsci/checks-api-plugin/pull/66

**Comment by XiongKezhi** [comment]
this feature has been implemented and is available after 1.4.0, see more: https://github.com/jenkinsci/checks-api-plugin/releases

**Comment by bochen87** [comment]
this seems really nice, can you please provide an example of how to use this in a Jenkinsfile pipeline?
