### ISSUE TITLE
Option to disable default notifications

### ISSUE THREAD

**Issue by mxsxs2** [jenkinsci/github-checks-plugin#93]
Hi, 
When Jenkins is added to GitHub it produces two checks for each PRs by default. This behavior can be disabled with [Skip Notifications Trait plugin](https://github.com/jenkinsci/skip-notifications-trait-plugin)
![image](https://user-images.githubusercontent.com/13612429/102800418-c0ea9600-43ab-11eb-8daa-a343d7b9e8ff.png)
I am thinking that it would be a great addition to Github Checks Plugin to contain this feature and allow us to toggle in configuration.

The two plugins works together well at the moment, but the configuration takes a bit longer as we need to add two Behaviours to each pipeline.
![image](https://user-images.githubusercontent.com/13612429/102800839-571ebc00-43ac-11eb-9875-2e3d08794360.png)

**Comment by XiongKezhi** [comment]
Thanks for that request, we'll support that. 

At the beginning of this project, we did consider adding this feature but eventually not since we have other things in higher priorities.
